### ISSUE TITLE
TUI default item not always selected

### ISSUE THREAD

**Issue by atrent** [shreyanshk/boottorrent#34]
in tui the default starting item (if it's not the first one in the list) is not automatically selected so it's a bit confusing for the user

**Comment by shreyanshk** [comment]
It now highlights the default OS.
Please note that the order of OSs will always remain random. It's because Golang intentionally randomly selects next item (without replacement) from map/list in a 'for' loop to ensure that there are no hidden dependencies on the access order and to force the programmer to ensure correct execution without depending on access order.
